name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request
  # events but only for the master branch
  push:
    branches:
      - '*'
  pull_request:
    branches: [main, develop, release]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that
    # will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access it
      - uses: actions/checkout@v2

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        run: yarn

      # Run test suites
      - name: Run test suites
        run: yarn test
